apiVersion: batch/v1
kind: Job
metadata:
  name:  hello-job
spec:
  template:
    spec:
      containers:
        - image:  busybox
          name:  busybox
          command: ["echo", "Hello Kubernetes!!"]
      restartPolicy: Never