apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-node-app
  labels:
    app: node-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata: 
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: shaiful161003/node-web-app
        ports:
        - containerPort: 8080