apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  labels:
    app: node-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: shaiful161003/node-web-app
        ports:
        - containerPort: 80
        resources:
          limits: 
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "o.2"
            
